### ISSUE TITLE
give cards `cursor: pointer;` so folks know they're clickable

### ISSUE THREAD

**Issue by zackkrida** [aholtzman/developer-portfolio#1]
I'd suggest adding `cursor: pointer` in here so the little hand cursor shows on hover of a card.

This site looks _greeeeeeaaaaaaaaaaatttttttt_ 🔥 🔥 🔥 

https://github.com/aholtzman/developer-portfolio/blob/c94ed763829175be91db030fc7a1a6525ce1dceb/src/components/devCard.js#L5-L15

**Comment by aholtzman** [comment]
I will, good catch. thank you.

**Comment by aholtzman** [comment]
put in place - better UX for it.
